### ISSUE TITLE
ReadMe.md File Issuse

### ISSUE THREAD

**Issue by BANDI-Plan** [C3-PENTA/RSU-ACCESS-CONTROL#1]
Readme.md 내용이 추가되어야 할 것으로 보입니다.
추후 SDP에 대한 간단한 설명 추가해주시기 바랍니다.

**Comment by YunKeon112** [comment]
확인하였습니다. 
ACCESS-CONTROL 에 대한 Read.me 파일을 작성 중이며 추후 SDP에 관련한 설명을 추가하도록 하겠습니다.
